name: depup
on:
  schedule:
    - cron:  '14 1,7,13,19 * * *'
  workflow_dispatch:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lemyst/action-depup/with-pr@allow-prelease
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile
          version_name: TERRAFORM_VERSION
          repo: hashicorp/terraform
      - uses:  lemyst/action-depup/with-pr@allow-prelease
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile
          version_name: TOFU_VERSION
          repo: opentofu/opentofu
      - uses:  lemyst/action-depup/with-pr@allow-prelease
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile
          version_name: TERRAGRUNT_VERSION
          repo: gruntwork-io/terragrunt
